In [4]:
l = [0,1,2,3,4]
print(l[1])
print(l[1:3])

1
[1, 2]


In [7]:
import numpy as np
arr = np.array(1)
arr

array([0, 1, 2, 3, 4])

In [9]:
arr[[1,3]]

array([1, 3])

In [10]:
cond = arr >= 3
cond

array([False, False, False,  True,  True])

In [14]:
np.random.randn(10)  # 正态分布

array([-0.2469375 ,  0.23200482,  0.06947384,  0.5821849 , -2.8172271 ,
        0.75598023, -0.83025188,  0.44059637,  1.10191164,  1.372852  ])

In [15]:
np.linspace(1,99,50)  # 等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [28]:
np.set_printoptions(suppress = True)  # 不显示科学记数法
np.logspace(0, 10, base = 3, num = 11)  # 等比数列
# shift+tab 提示参数

array([    1.,     3.,     9.,    27.,    81.,   243.,   729.,  2187.,
        6561., 19683., 59049.])

In [29]:
# 二维数组
np.random.randint(0,10,size=(3,5))

array([[5, 3, 1, 0, 6],
       [6, 3, 6, 1, 3],
       [1, 4, 3, 0, 8]])

In [30]:
# 三维数组
np.random.randint(0,10,size=(2,3,5))

array([[[2, 3, 1, 9, 2],
        [8, 0, 6, 6, 6],
        [8, 2, 0, 3, 2]],

       [[3, 3, 2, 7, 5],
        [5, 1, 7, 9, 3],
        [1, 3, 0, 0, 6]]])

# 数据存取

In [2]:
import numpy as np
arr = np.random.random(size = (3,5))
arr

array([[0.98240483, 0.0681553 , 0.1477781 , 0.95964978, 0.38939399],
       [0.20663032, 0.155677  , 0.31901278, 0.95966158, 0.45188823],
       [0.77780984, 0.77040053, 0.87524335, 0.58102748, 0.62755901]])

In [5]:
arr.shape  # 形状

(3, 5)

In [7]:
arr.size

15

In [6]:
 arr.dtype  # 数据类型 float 64 （64位）

dtype('float64')

In [8]:
arr.ndim  # 维度

2

In [9]:
arr.itemsize  # 每个元素大小

8

In [14]:
for i in range(0,10,3):
    print(i)

0
3
6
9


In [17]:
arr = np.arange(0,10,3)
np.save('./data1', arr)  # IO存

In [18]:
np.load('./data1.npy')  # IO取

array([0, 3, 6, 9])

In [26]:
x = np.random.randn(5)
y = np.arange(0, 10, 2)
np.savez("some_array.npz", xarr = x, yarr = y)  # 保存多个

In [27]:
np.load('some_array.npz')['yarr']

array([0, 2, 4, 6, 8])

# 数据类型

In [28]:
arr = np.array([2,4,5],dtype = np.int8)
arr

array([2, 4, 5], dtype=int8)

In [30]:
np.save('./data2_int8', arr)

In [29]:
arr = np.array([2,4,5],dtype = np.int64)
arr

array([2, 4, 5])

In [3]:
np.save('./data3_int64.npy', arr)

NameError: name 'arr' is not defined

In [5]:
import numpy as np
arr = np.arange(-128,1,dtype = np.int8)
arr = np.arange(-128,128,dtype = np.int8)
arr

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [9]:
arr2 = np.arange(-129,128,dtype = np.uint8)
arr2

/var/folders/9x/6l63xm_n0tv0q7h1snzflcyh0000gn/T/ipykernel_39385/3300433855.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -129 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr2 = np.arange(-129,128,dtype = np.uint8)
/var/folders/9x/6l63xm_n0tv0q7h1snzflcyh0000gn/T/ipykernel_39385/3300433855.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -128 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr2 = np.arange(-129,128,dtype = np.uint8)


array([127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
       218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
       231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
       244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,   0,
         1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  5

In [12]:
np.array(arr2).astype(np.uint16)

array([127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
       218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
       231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
       244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,   0,
         1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  5

# 数组运算

In [30]:
nd = np.random.randint(0,10,size = (3,5))
nd

array([[0, 5, 0, 9, 7],
       [7, 2, 6, 1, 4],
       [7, 4, 4, 2, 9]])

In [31]:
nd ** 3

array([[  0, 125,   0, 729, 343],
       [343,   8, 216,   1,  64],
       [343,  64,  64,   8, 729]])

In [32]:
np.power(nd, 3)

array([[  0, 125,   0, 729, 343],
       [343,   8, 216,   1,  64],
       [343,  64,  64,   8, 729]])

In [33]:
nd / 2

array([[0. , 2.5, 0. , 4.5, 3.5],
       [3.5, 1. , 3. , 0.5, 2. ],
       [3.5, 2. , 2. , 1. , 4.5]])

In [34]:
nd % 2

array([[0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [35]:
nd // 2

array([[0, 2, 0, 4, 3],
       [3, 1, 3, 0, 2],
       [3, 2, 2, 1, 4]])

In [36]:
nd > 5

array([[False, False, False,  True,  True],
       [ True, False,  True, False, False],
       [ True, False, False, False,  True]])

In [37]:
nd == 6

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [45]:
nd += 100
nd

array([[133, 133, 133, 133, 133],
       [133, 133, 133, 133, 133],
       [133, 133, 133, 133, 133]])

In [46]:
nd //= 3
nd

array([[44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44]])

# 索引和切片

## 一维数组

In [48]:
arr = np.random.randint(0, 100, size = 10)
arr

array([50, 46,  5, 52, 99, 14,  9, 29, 40, 95])

In [49]:
arr[[0,3,5]]

array([50, 52, 14])

In [50]:
arr[3:6]  # 切片，且当

array([52, 99, 14])

In [51]:
arr[3:6:2]  # 指定步长

array([52, 14])

In [52]:
arr[:]

array([50, 46,  5, 52, 99, 14,  9, 29, 40, 95])

In [53]:
arr[::-1]

array([95, 40, 29,  9, 14, 99, 52,  5, 46, 50])

In [54]:
arr[::-3]

array([95,  9, 52, 50])

## 二维数组

In [55]:
arr = np.random.randint(0, 100, size = (3,5))
arr

array([[52, 99, 91, 13, 82],
       [ 0, 10, 47, 56, 35],
       [23, 19, 51, 70,  3]])

In [56]:
arr[0,2]

91

In [57]:
arr[1,[1,2]]

array([10, 47])

In [60]:
arr[[1,2],[3,4]]

array([56,  3])

In [64]:
arr[[1,2],3:]

array([[56, 35],
       [70,  3]])

In [65]:
arr[[1,2]][:,[3,4]]

array([[56, 35],
       [70,  3]])

In [66]:
arr[[0,2]][:,[0,2,4]]

array([[52, 91, 82],
       [23, 51,  3]])

In [67]:
arr[2,[2,4]] = 1024
arrm

array([[  52,   99,   91,   13,   82],
       [   0,   10,   47,   56,   35],
       [  23,   19, 1024,   70, 1024]])

## 花式数据

In [68]:
arr = np.random.randint(0, 100, size = 20)
arr

array([11, 91, 89, 87, 73, 94,  0, 87, 61,  1, 47, 41, 91, 52, 80, 77, 81,
       11, 91, 27])

In [69]:
arr[[3,5,7]]

array([87, 94, 87])

In [71]:
cond = arr > 60
arr[cond]

array([91, 89, 87, 73, 94, 87, 61, 91, 80, 77, 81, 91])

In [73]:
cond1 = arr < 30
cond2 = arr >80
cond = cond1 | cond2  # 或运算
arr[cond]

array([11, 91, 89, 87, 94,  0, 87,  1, 91, 81, 11, 91, 27])

In [80]:
import random
random.randint(1,2)

2

In [86]:
random.randrange(-1, 2)

-1

In [88]:
'%s%s' %('1', '2')

'12'

In [ ]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
